services:
  catalogue:
    build: ./catalogue-service
    ports:
      - "8081:8081"

  order:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - CATALOGUE_URL=http://catalogue:8081